title: Stefan Neuhaus
baseurl: "https://stefanneuhaus.org/"
copyright: '© 2018 Stefan Neuhaus'

module:
  imports:
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy/v5

removePathAccents: true
summaryLength: 30
enableEmoji: true
enableRobotsTXT: true
footnoteReturnLinkContents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
permalinks:
  posts: /post/:slug/
  categories: /category/:slug/
disableAliases: true
outputs:
  home: [HTML, RSS, WebAppManifest]
imaging:
  resampleFilter: lanczos
markup:
  _merge: deep
  highlight:
    codeFences: false
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 70
security:
  _merge: deep
